env:
  aseApiKeyId: 6Q3W37Y8XIDPGEKX06ASNM7PZR87EX0V
  aseApiKeySecret: O2VUV2HXKU92Y27OE1HNRR147VP9CCWI
  compiledArtifactFolder: none
  scanConfig: Normal scan
  aseAppName: ${{GITHUB.EVENT.REPOSITORY.NAME}}
  aseHostname: winappscan.lab.local
  aseToken: C:\ProgramData\HCL\AppScanSource\config\ounceautod.token
  sevSecGw: highIssues
  maxIssuesAllowed: 1000
  WorkingDirectory: ${{GITHUB.WORKSPACE}}
  BuildNumber: ${{GITHUB.RUN_NUMBER}}

name: HCL AppScan Source
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Scan SAST
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-GithubActions-Integration/main/scripts/appscanase_create_application_ase.ps1 -OutFile appscanase_create_application_ase.ps1
          .\appscanase_create_application_ase.ps1
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-GithubActions-Integration/main/scripts/appscansrc_create_config_scan_folder.ps1 -OutFile appscansrc_create_config_scan_folder.ps1
          .\appscansrc_create_config_scan_folder.ps1
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-GithubActions-Integration/main/scripts/appscansrc_scan.ps1 -OutFile appscansrc_scan.ps1
          .\appscansrc_scan.ps1
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-GithubActions-Integration/main/scripts/appscansrc_publish_assessment_to_enterprise.ps1 -OutFile appscansrc_publish_assessment_to_enterprise.ps1
          .\appscansrc_publish_assessment_to_enterprise.ps1
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-GithubActions-Integration/main/scripts/appscansrc_check_security_gate.ps1 -OutFile appscansrc_check_security_gate.ps1
          .\appscansrc_check_security_gate.ps1
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-GithubActions-Integration/main/scripts/appscansrc_export_sarif.ps1 -OutFile appscansrc_export_sarif.ps1
          .\appscansrc_export_sarif.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: Upload report
          path: ${{GITHUB.EVENT.REPOSITORY.NAME}}-${{GITHUB.RUN_NUMBER}}.pdf
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: src2result.sarif
          category: my-analysis-tool
